[env:esp32-c3-devkitm-1]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = COM6
upload_speed = 921600
board_build.flash_mode = dio
build_flags = 
	-Wall
	-Os
	-D BUILD_NUMBER=1

lib_deps = 
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
	; xiaozi/Blinker@0.2.5 已移除（不兼容ESP32-C3）
